### ISSUE TITLE
Create CICD action to upload to firebase storage

### ISSUE THREAD

**Issue by olisedoc** [flux-ad/RevitPluginRelease#1]
These installers should not be downloaded from github directly, but instead from our own cloud storage. 
Therefore we should setup a github action which uploads the installer files to firebase storage on new commits to master branch.

NOTE: When finished, we should discuss whether this repo is necessary anymore? or we should just upload the files to firebase storage directly from the main Repo.

### Possible solution (generated with chatGPT)

You can create a GitHub Actions workflow that uploads the specified files to Firebase Storage whenever a new commit is made to the master branch. You can use the `Firebase CLI` to handle the upload process. Here's a sample workflow file:

1. First, create a `.github/workflows` folder in your repository if it doesn't already exist.

2. Next, create a new YAML file in the `.github/workflows` folder, for example, `firebase_upload.yml`.

3. Add the following code to the `firebase_upload.yml` file:

```yaml
name: Upload Installers to Firebase Storage

on:
  push:
    branches:
      - master

jobs:
  upload-installers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Login to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase login:ci --token "$FIREBASE_TOKEN"

    - name: Upload installers to Firebase Storage
      run: |
        firebase storage:upload Fast2020.msi --path /installers/Fast2020.msi
        firebase storage:upload Fast2021.msi --path /installers/Fast2021.msi
        firebase storage:upload Fast2022.msi --path /installers/Fast2022.msi
```

4. This workflow assumes you have set up a Firebase project and have the `Firebase CLI` installed locally. If you haven't already, follow the instructions in the [Firebase documentation](https://firebase.google.com/docs/cli#install-cli-mac-linux) to set up the CLI and generate a token.

5. Once you have the token, add it to your GitHub repository secrets. Go to the repository settings, click on "Secrets," then click "New repository secret." Name the secret "FIREBASE_TOKEN" and paste the token you generated in the previous step.

With this workflow in place, whenever a commit is made to the master branch, the GitHub Action will trigger, and the specified files will be uploaded to the Firebase Storage path "/installers/".
